name: Tests
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0"]

    steps:
      - uses: actions/checkout@main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        run: |
          bundle exec rake test
